name: alfred
description: A performant, expressjs like web server / rest api framework thats easy to use and has all the bits in one place.
version: 1.1.0+0
repository: https://github.com/rknell/alfred

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  mime: ^1.0.0
  mime_type: ^1.0.0
  queue: ^3.1.0
  path: ^1.8.2
  meta: ^1.3.0

dev_dependencies:
  test: ^1.21.4
  web_socket_channel: ^2.0.0
  logging: ^1.0.1
  http: ^0.13.2
  lints: ^2.0.1
